blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/ScottKirvan/QuKi-Notes/discussions
    about: Ask questions and discuss ideas here.
  - name: Discord
    url: https://discord.gg/TSKHvVFYxB
    about: Chat with the community on Discord.
